version: "3"
services:
    frontend:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        volumes:
            - ./frontend:/app
        command: ["npm", "run", "serve"]
        ports:
            - "8082:8081"
